query GithubProjects {
  github {
    viewer {
      email
      repositories(
        first: 100
        privacy: PUBLIC
        orderBy: { field: UPDATED_AT, direction: DESC }
      ) {
        edges {
          node {
            name
            nameWithOwner
            url
            description
          }
        }
      }
    }
  }
}
